### ISSUE TITLE
Specify release acceptance/testing criteria for upstream Ooni releases.

### ISSUE THREAD

**Issue by nathan-at-least** [m-lab-tools/ooni-support#33]
A well documented acceptance criteria for new Ooni releases could help M-Lab know what to expect, and Ooni to know what to strive for.  This could be in the form of a checklist that the deployment works through prior to pushing a new deployment.  It need not be too detailed.  A suggested checklist would be:
- [ ] Ensure the release to be deployed follows Ooni's own documented standard for [Release Procedure](https://github.com/TheTorProject/ooni-spec/blob/master/Release-Procedure.md):
  - [ ] The automated [test reports from coveralls](https://coveralls.io/r/TheTorProject/ooni-probe) are acceptable.
  - [ ] The release is properly tagged and signed by the [official Ooni process](https://github.com/TheTorProject/ooni-spec/blob/master/Release-Procedure.md#tagging-and-signing-of-a-release).
- [ ] Verify that the appropriate M-Lab sanctioned test decks will be served/packaged.
- [ ] Deploy to a test slice. (see pull #36 with improved docs for this.)
- [ ] Run a smoke test which is documented.
- [ ] Deploy to production. (same as #36 instructions.)
- [ ] Run a smoke test against production as above.

**TODO:** This document should be linked to from [ooni-spec Release Procedure - Code Review section](https://github.com/TheTorProject/ooni-spec/blob/master/Release-Procedure.md#code-review).

This is related to #30.

Note that the [Ooni Release Procedure](https://github.com/TheTorProject/ooni-spec/blob/master/Release-Procedure.md) contains an allusion that Ooni tests and the backend packages "must pass the approval from m-lab before they will be fit to run on their platform."  Once this ticket is closed by defining the acceptance criteria, crosslinking that Ooni doc to the M-Lab specification will help integrate the Ooni release & M-Lab deployment processes.
